food=["pasta","ice cream"]
print(food)
food.append("pancakes")
print(food)
food.insert(2,"pizza")
print(food)
food.sort()
print(food)
food.remove("pasta")
print(food)
food.pop(2)
print(food)
food.reverse()
print(food)